### ISSUE TITLE
Error message when selecting action

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph-codecov#8]
Using Sourcegraph.com, when I select the below.

![screen shot 2018-09-17 at 1 57 21 pm](https://user-images.githubusercontent.com/133014/45649965-b4b35800-ba81-11e8-9342-def9fd8e4eea.png)

Produced the error message.

`Request commands/$executeCommand failed with message: Cannot read property 'showInputBox' of undefined`.

**Comment by sqs** [comment]
This occurs because there is no code file open, and `showInputBox` is a method on a window (which is only non-null when there's a code file). Kind of defeats the point I mentioned in https://github.com/sourcegraph/sourcegraph/issues/13288, haha. I will make this item show up only when there is a code file for now.
